### ISSUE TITLE
Add Top-P, Frequency Penalty and Presence Penalty

### ISSUE THREAD

**Issue by Marcus-Arcadius** [wieslawsoltes/ChatGPT#28]
As a feature request could you please integrate the parameters `top_p`, `frequency_penalty`, and `presence_penalty` into the application? It would be greatly appreciated and significantly enhance its functionality and customizability.

**Comment by wieslawsoltes** [comment]
They are already available just not surfaced via GUI, will add them.

**Comment by wieslawsoltes** [comment]
Added
