### ISSUE TITLE
when i type Chinese there some errors,can you help me?

### ISSUE THREAD

**Issue by pcfengzi** [wieslawsoltes/ChatGPT#29]
![image](https://user-images.githubusercontent.com/6889779/227502223-3b353430-2826-477b-9f31-1f241322fbbc.png)

**Comment by wieslawsoltes** [comment]
Probably included Inter font doesn't support those chars. You would need to include and set Chinese compatible font. It adds a lot of download size to program unfortunately.

**Comment by pcfengzi** [comment]
Where i can add this font？this is the first time that i use Avalonia .

**Comment by wieslawsoltes** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/8938
