### ISSUE TITLE
how about use text-davinci-002-render model?

### ISSUE THREAD

**Issue by SuperWildFireFox** [wieslawsoltes/ChatGPT#3]
It seems that text-davinci-002-render is origin ChatGPT model. It will generate more interesting answer.

**Comment by wieslawsoltes** [comment]
No official api docs, not sure if it will work at all

**Comment by wieslawsoltes** [comment]
There is leaked `text-chat-davinci-002-20221122` but `text-davinci-003` seems more factual.

**Comment by wieslawsoltes** [comment]
No possible anymore, need to wait for new api for chatgpt, added option to set model so user can choose new models.
