### ISSUE TITLE
Add a setting that allows users to input their Own OpenAI proxy URL.

### ISSUE THREAD

**Issue by littlesmilelove** [wieslawsoltes/ChatGPT#34]
Sometimes, we may need to deploy a reverse proxy to the ChatGPT API. Can you add a setting for users to input their own OpenAI API URL?

**Comment by jinweijie** [comment]
Hello, I created a PR for this using the environment variable to be able to use Azure OpenAI service, please check, BTW thanks for the great app!

**Comment by wieslawsoltes** [comment]
Added SetApiUrl to IChatService method to override api url:
```
        var chat = Defaults.Locator.GetService<IChatService>();
        chat.SetApiUrl("you api url");
```
