### ISSUE TITLE
Add option to import Models like https://github.com/nomic-ai/gpt4all makes available.

### ISSUE THREAD

**Issue by cocoonkid** [wieslawsoltes/ChatGPT#35]
Add option to import Models like https://github.com/nomic-ai/gpt4all makes available.

This would be so highly appreciated you wouldn't believe.

**Comment by wieslawsoltes** [comment]
You can already change models, check Model setting.

**Comment by cocoonkid** [comment]
Yes but these are the models that are offered via the API.
(One suggestiion here would be to contraint the selection to only these offered by the API and make it a dropdown..a lot less human error)

what I mean is the model chatgpt4all offers to Download.
So we can add these.

**Comment by wieslawsoltes** [comment]
Not planned, using OpenAI or Azure OpenAI services for now.
