### ISSUE TITLE
Allow a user to couples specifc settings with specific directions. 

### ISSUE THREAD

**Issue by cocoonkid** [wieslawsoltes/ChatGPT#40]
Allow a user to couples specifc settings with specific directions. 

For example it would allow me to create certain directions only with GPT-4 and others with 3.5-turbo etc.

![image](https://user-images.githubusercontent.com/43231640/229104331-48c58f2b-4fae-48f6-997b-bb22bc2ddf30.png)

**Comment by wieslawsoltes** [comment]
You can already do that using set button (checkmark icon or the right):
![image](https://user-images.githubusercontent.com/2297442/229374229-ea610178-1a0f-42c7-9938-11579cd0ff8e.png)
