### ISSUE TITLE
Name collision with /usr/bin/chat

### ISSUE THREAD

**Issue by cocoonkid** [wieslawsoltes/ChatGPT#55]
I renamed /usr/bin/chat to /usr/bin/chatold for now but I would like to suggest to give the project a cool name to distinguish it from all the other "chat*" available.

**Comment by wieslawsoltes** [comment]
What's the other chat app ?

**Comment by wieslawsoltes** [comment]
Pushed fix https://github.com/wieslawsoltes/ChatGPT/commit/561a7b9716edeb6dfb786893982c1a072d48de4e

New .NET tool command name is `chatgpt`
