### ISSUE TITLE
 customize the OpenAI base URL

### ISSUE THREAD

**Issue by dashi6174** [wieslawsoltes/ChatGPT#56]
Adding the ability to customize the OpenAI base URL would be desirable.

**Comment by wieslawsoltes** [comment]
Duplicate https://github.com/wieslawsoltes/ChatGPT/issues/34

**Comment by wieslawsoltes** [comment]
Added readme section https://github.com/wieslawsoltes/ChatGPT/blob/main/README.md#overriding-openai-api-url
