### ISSUE TITLE
doesn't recognize other models

### ISSUE THREAD

**Issue by bitdisaster** [wieslawsoltes/ChatGPT#57]
Any model I tried besides gpt-3.5-turbo gives an error like 'The model: `gpt-4` does not exist'

**Comment by wieslawsoltes** [comment]
gpt-4 works without issues

**Comment by wieslawsoltes** [comment]
@bitdisaster You need to apply for access

**Comment by wieslawsoltes** [comment]
https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

**Comment by bitdisaster** [comment]
Ah ok,  makes sense. Thanks!
