### ISSUE TITLE
Please remove that annoying clippy image 

### ISSUE THREAD

**Issue by wvhulle** [wieslawsoltes/ChatGPT#64]
It fucks up the android client usability

**Comment by wieslawsoltes** [comment]
No

**Comment by wieslawsoltes** [comment]
If you want you can do custom build without it, it's OSS project.

**Comment by wvhulle** [comment]
But you do know it is in front of the buttons right?

**Comment by wieslawsoltes** [comment]
> But you do know it is in front of the buttons right?

Can you provide screenshot

**Comment by wvhulle** [comment]
But you do know it is in front of the buttons right?



![Screenshot_2023-05-24-13-00-36-76_e80a02a50b17ca25b0b7999fda52e0cf.jpg](https://github.com/wieslawsoltes/ChatGPT/assets/7688680/e8d2e692-184e-45cf-993e-e6412634c1dd)

**Comment by wvhulle** [comment]
But you do know it is in front of the buttons right?



![Screenshot_2023-05-24-13-00-36-76_e80a02a50b17ca25b0b7999fda52e0cf.jpg](https://github.com/wieslawsoltes/ChatGPT/assets/7688680/e8d2e692-184e-45cf-993e-e6412634c1dd)

By the way, you know that Clippy is not exactly OSS?

**Comment by wieslawsoltes** [comment]
> By the way, you know that Clippy is not exactly OSS?

Well hopefully Microsoft will not put me in jail because then this project would be dead and you will have to live with those buttons overlapping.

Anyway the issue is not with image, just need to fix buttons.
