### ISSUE TITLE
API Error feedback

### ISSUE THREAD

**Issue by pr8x** [wieslawsoltes/ChatGPT#8]
API returned "Quota exceeded" error message. Would be nice to show these in red as the response message.

**Comment by wieslawsoltes** [comment]
Are you using latest version, it should be red.

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/ChatGPT/blob/37184ec129b0c177af3aa67bb16c03a8f3d1495d/ChatGPT.UI/Themes/Themes.axaml#L7

**Comment by pr8x** [comment]
Ah It was added already :) Nice!
